"/
"/ Syntastic
"/
" set statusline+=%#warningmsg#
" set statusline+=%{SyntasticStatuslineFlag()}
" set statusline+=%*

" let g:syntastic_always_populate_loc_list = 1
" let g:syntastic_auto_loc_list = 1
" let g:syntastic_check_on_open = 1
" let g:syntastic_check_on_wq = 0
" let g:ycm_server_python_interpreter = '/usr/bin/python'

"/
"/ ale
"/
let g:ale_fixers = {
\   'javascript': ['eslint'],
\}
let g:ale_fix_on_save = 1

"Add simple  highlight to removal
nmap <Leader><space> :nohlsearch<cr>
