default:
    @just --list --unsorted

alias r := run

# Run neovim flake
run:
    nix run .#

# Show neovim flake output
show:
    nix flake show

# Update flake
update:
    nix flake update

# Check flake
check:
    nix flake check