require 'rvim.ui.snacks'
require 'rvim.ui.tiny-diagnostics'
require 'rvim.ui.mini-indent'
require 'rvim.ui.indent'
require 'rvim.ui.highlight-colors'
require 'rvim.ui.notifications'
require 'rvim.ui.yazi'
-- require 'rvim.ui.oil'
require 'rvim.ui.grapple'
require 'rvim.ui.folding'
require 'rvim.ui.zen'