# powerlevel9k prompt theme
POWERLEVEL9K_MODE="nerdfont-complete"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time  root_indicator load_joined ram_joined)
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_left"

POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{cyan}\u256D\u2500%f"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{014}\u2570%F{cyan}\uF460%F{073}\uF460%F{109}\uF460%f "
# POWERLEVEL9K_PROMPT_ON_NEWLINE=true

POWERLEVEL9K_HOST_LOCAL_BACKGROUND="235"
POWERLEVEL9K_HOST_LOCAL_FOREGROUND="cyan"
POWERLEVEL9K_HOST_REMOTE_BACKGROUND="235"
POWERLEVEL9K_HOST_REMOTE_FOREGROUND="cyan"
POWERLEVEL9K_USER_ICON="\uF415" # 
POWERLEVEL9K_ROOT_ICON="\u26A1" # ⚡
POWERLEVEL9K_HOST_ICON="\uF109" # 
POWERLEVEL9K_HOST_ICON_FOREGROUND="red"
POWERLEVEL9K_HOST_ICON_BACKGROUND="black"
POWERLEVEL9K_SSH_ICON="\uF489"  # 
POWERLEVEL9K_DIR_HOME_BACKGROUND="cyan"
POWERLEVEL9K_DIR_HOME_FOREGROUND="black"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="cyan"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="black"
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="cyan"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="black"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="cyan"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="black"

POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND="235"
POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND="red"
# Segment in black and white
POWERLEVEL9K_LOAD_CRITICAL_BACKGROUND="235"
POWERLEVEL9K_LOAD_CRITICAL_FOREGROUND="cyan"
POWERLEVEL9K_LOAD_WARNING_BACKGROUND="235"
POWERLEVEL9K_LOAD_WARNING_FOREGROUND="cyan"
POWERLEVEL9K_LOAD_NORMAL_BACKGROUND="235"
POWERLEVEL9K_LOAD_NORMAL_FOREGROUND="cyan"
# Colorize only the visual identifier
POWERLEVEL9K_LOAD_CRITICAL_VISUAL_IDENTIFIER_COLOR="001"
POWERLEVEL9K_LOAD_WARNING_VISUAL_IDENTIFIER_COLOR="003"
POWERLEVEL9K_LOAD_NORMAL_VISUAL_IDENTIFIER_COLOR="002"

POWERLEVEL9K_RAM_BACKGROUND="235"
POWERLEVEL9K_RAM_FOREGROUND="cyan"

POWERLEVEL9K_STATUS_OK_BACKGROUND="235"
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="235"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="red"

POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND="235"
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND="magenta"
POWERLEVEL9K_COMMAND_EXECUTION_TIME_ICON="\u231A"

POWERLEVEL9K_VCS_CLEAN_BACKGROUND="005"
POWERLEVEL9K_VCS_CLEAN_FOREGROUND="255"
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="255"
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="005"
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="255"
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="005"

ZSH_THEME="powerlevel9k/powerlevel9k"