# powerlevel9k prompt theme
POWERLEVEL9K_MODE="nerdfont-complete"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(prompt_char os_icon dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time)
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_left"
POWERLEVEL9K_SHORTEN_DELIMITER=""

POWERLEVEL9K_PROMPT_CHAR_BACKGROUND="232"
POWERLEVEL9K_PROMPT_CHAR_FOREGROUND="242"

POWERLEVEL9K_HOST_LOCAL_BACKGROUND="232"
POWERLEVEL9K_HOST_LOCAL_FOREGROUND="242"
POWERLEVEL9K_HOST_REMOTE_BACKGROUND="255"
POWERLEVEL9K_HOST_REMOTE_FOREGROUND="232"
POWERLEVEL9K_USER_ICON="\uF415" # 
POWERLEVEL9K_ROOT_ICON="\u26A1" # ⚡
POWERLEVEL9K_HOST_ICON="\uF109" # 
POWERLEVEL9K_HOST_ICON_FOREGROUND="red"
POWERLEVEL9K_HOST_ICON_BACKGROUND="black"
POWERLEVEL9K_SSH_ICON="\uF489"  # 
POWERLEVEL9K_DIR_HOME_BACKGROUND="232"
POWERLEVEL9K_DIR_HOME_FOREGROUND="242"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="232"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="242"
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="232"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="242"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="232"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="red"
POWERLEVEL9K_OS_ICON_BACKGROUND="232"
POWERLEVEL9K_OS_ICON_FOREGROUND="242"

POWERLEVEL9K_STATUS_OK_BACKGROUND="232"
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="232"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="red"

POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND="232"
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND="magenta"
POWERLEVEL9K_COMMAND_EXECUTION_TIME_ICON="\u231A"

POWERLEVEL9K_VCS_CLEAN_BACKGROUND="23"
POWERLEVEL9K_VCS_CLEAN_FOREGROUND="252"
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="252"
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="23"
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="252"
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="23"
POWERLEVEL9K_HIDE_BRANCH_ICON=true

ZSH_THEME="powerlevel10k/powerlevel10k"
