require 'rvim.misc.mini'
require 'rvim.misc.session'
require 'rvim.misc.comment'
require 'rvim.misc.flash'
-- require 'rvim.misc.obsidian'
require 'rvim.misc.render-markdown'
require 'rvim.misc.search-replace'
